.ad l
.TH XRE_INFO 3 2020-03-14 "Ver. 1.0.0" "XRE Library Documentation"
.nh \" Turn off hyphenation.
.SH NAME
\fBxlibconf\fR, \fBxlibvers\fR - routines for obtaining extended regular expression (XRE) library information
.SH SYNOPSIS
\fB#include "xre.h"\fR
.HP 2
\fBint xlibconf(void);\fR
.HP 2
\fBchar *xlibvers(void);\fR
.SH DESCRIPTION
These routines provide information about the XRE library.
.PP
The \fBxlibconf\fR() routine returns configuration information about the library; that is, its build options.  The returned
integer is the bitwise OR of zero or more of the following flags:
.sp
.PD 0
.RS 5
.IP ConfigWChar 20
Wide characters (\fIwchar_t\fR) are supported.
.IP ConfigMultibyte 20
Multibyte characters are supported.
.IP ConfigApprox 20
Approximate matching is supported.
.IP ConfigReverse 20
Reversed patterns and backward searching are supported.
.RE
.PD
.PP
Note that if the ConfigMultibyte flag is set, the ConfigWChar flag will also be set.
.PP
The \fBxlibvers\fR() routine returns a human-readable library version string.
.SH SEE ALSO
xre(3), xre_approx(3), xre_core(3), xre_format(7), xre_reverse(3)
